apiVersion: v1
kind: ConfigMap
metadata:
  name: dp-config
  namespace: integration
data:
  auto-startup.cfg: |-
    top; configure terminal;

    rest-mgmt
      admin-state enabled
      local-address 0.0.0.0 5554
    exit

    web-mgmt
      admin-state enabled
      local-address 0.0.0.0 9090
    exit